[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "weatherfetch"
version = "0.1.1"
description = "A neofetch-inspired CLI weather tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
]

[project.scripts]
weatherfetch = "weatherfetch.fetch:main"
